### ISSUE TITLE
How to use cassandra store outside Responsive SaaS

### ISSUE THREAD

**Issue by Chuckame** [responsivedev/responsive-pub#266] opened 2024-03-19 18:33 UTC
Hello,

## Context
We are using kafka streams to aggregate and join events with big states, while our load is kind of constant and not that high (1k-3K evt/s). But when it comes to reset the app and restart from scratch, reconsuming the input topics takes a lot of time (reaching the resources limits), so we ended up with a kind of blue/green: when needing an app reset, we warm up a second instance of the topology in parallel of the currently live instance, and when this new instance is "live" (e.g. the lag is near to 0), then we stop the previous instance... Yeah, that comes with a lot of issues, but whatever, you have the main issue!

Now, the idea would be to put the input topics data inside a "long term" DB to avoid reconsuming the data each time we need an app reset. Also, it will permit a better scaling as we are mainly setting the number of threads/nodes regarding  the initial/re-consumption instead of regarding the live load. And as the icing-on-the-cake, the cassandra stores would be mutualized between apps.

## Question
Is the cassandra key-value store usable outside your SaaS ? If yes, how would it be usable, which configuration, and how would it behaves regarding the app reset tooling as it removes internal topics ?

_I've known this open-source library from the kafka summit few hours ago, great presentation btw, I hope the replay will be quickly available 😄_ 

Thanks, and great job for all the work!

**Comment by agavra** [comment] 2024-03-20 09:48
@Chuckame - the problems you're facing are exactly why we've built this (and I'm glad you enjoyed the summit talk)! You should be able to use this repository without our managed service to connect to your Cassandra cluster - you can follow our existing [quickstart](https://docs.responsive.dev/getting-started/quickstart) to get a sense of what you'd need to do to configure it (it runs against OSS docker containers for Kafka/Scylla so just configure it to use your own endpoints instead of the local ones).

> and how would it behaves regarding the app reset tooling as it removes internal topics ?

It doesn't actually remove the internal topics, it just doesn't rely on them for restoration. You can configure changelog truncation if you want but we don't actually recommend that unless you're certain you'll never want to rebootstrap from changelog. We've found having the changelog useful (for example) if you want to bootstrap a new Cassandra cluster (for example with different hardware) without having to run a major repair on your live cluster.

I'll close this ticket for now since it's not a bug/feature request, but feel free to drop into our [discord](https://discord.gg/jEk8JvjJrg) if you need more interactive help getting it set up!

We also take external contributions if you're eager to try it out for yourself :)

**Closed by agavra** 2024-03-20 09:48 UTC
